### ISSUE TITLE
No such module 'FindSurfaceFramework'

### ISSUE THREAD

**Issue by 179992096** [CurvSurf/FindSurface-GUIDemo-iOS#1] opened 2021-09-27 09:51 UTC
I follow step 1 ～ step 3 to use this framework, but i can't use 
<img width="754" alt="1" src="https://user-images.githubusercontent.com/11768708/134886481-bc9d8a85-729a-435b-b607-c25cfd382234.png">
.
<img width="1030" alt="2" src="https://user-images.githubusercontent.com/11768708/134886508-99a21016-a0ba-4b95-bb1b-7bfbd74d0938.png">
<img width="932" alt="3" src="https://user-images.githubusercontent.com/11768708/134886532-b978eef8-9443-4dfb-80ad-1c4a1c7e97a3.png">

**Comment by CurvSurf** [comment] 2021-09-27 11:13
We reproduced the issue, and now we're finding the cause of the case.
We will notify you as soon as we fix the problem.

Thank you!

**Comment by CurvSurf** [comment] 2021-09-28 05:36
Still working on the case. Reproducing the issue has not always worked.

By the way, the library for iOS does not support x86 architecture (i.e., the iOS simulator in Xcode). Make sure you set your actual device to the target machine if you have one. Otherwise, set the target machine as follows:

![screenshot](https://user-images.githubusercontent.com/35439745/135028414-448fc1f5-1868-4508-8cae-2d5ba46d5ed1.png)

**Comment by 179992096** [comment] 2021-09-28 05:53
> Still working on the case. Reproducing the issue has not always worked.
> 
> By the way, the library for iOS does not support x86 architecture (i.e., the iOS simulator in Xcode). Make sure you set your actual device to the target machine if you have one. Otherwise, set the target machine as follows:
> 
> ![screenshot](https://user-images.githubusercontent.com/35439745/135028414-448fc1f5-1868-4508-8cae-2d5ba46d5ed1.png)

I'm using iphone13 Pro max, which hasn't been solved yet. I'm using apple demo，Thk~

**Comment by CurvSurf** [comment] 2021-09-28 07:09
> > Still working on the case. Reproducing the issue has not always worked.
> > By the way, the library for iOS does not support x86 architecture (i.e., the iOS simulator in Xcode). Make sure you set your actual device to the target machine if you have one. Otherwise, set the target machine as follows:
> > ![screenshot](https://user-images.githubusercontent.com/35439745/135028414-448fc1f5-1868-4508-8cae-2d5ba46d5ed1.png)
> 
> I'm using iphone13 Pro max, which hasn't been solved yet. I'm using apple demo，Thk~

The cause of the reproduced issue here turned out to be due to the signing issue. There is a field named "team" on the "Signing & Capabilities" page, of which the default value is "none." The field must be reassigned as your team name. Please check if it is appropriately assigned.

![signing](https://user-images.githubusercontent.com/35439745/135039812-a3025fae-ca9a-49b8-aa97-8f7d2a89b70a.png)

**Comment by CurvSurf** [comment] 2021-09-30 10:51
> > Still working on the case. Reproducing the issue has not always worked.
> > By the way, the library for iOS does not support x86 architecture (i.e., the iOS simulator in Xcode). Make sure you set your actual device to the target machine if you have one. Otherwise, set the target machine as follows:
> > ![screenshot](https://user-images.githubusercontent.com/35439745/135028414-448fc1f5-1868-4508-8cae-2d5ba46d5ed1.png)
> 
> I'm using iphone13 Pro max, which hasn't been solved yet. I'm using apple demo，Thk~


Any progress yet?
If you solved the problem, would you share with us the cause and how you solved it?

We will close the case if there is no comment about the issue in a week.

**Closed as completed** 2021-10-29 14:43 UTC
Labels: bug

**Comment by yura** [comment] 2021-11-13 16:31
I have the same issue. And I sign it using my personal key (free account)

**Comment by RishabhBajaj25** [comment] 2023-04-04 21:08
I have the same issue while building on iPhone14 Pro
